[package]
name = "syncat-stylesheet"
version = "0.1.0"
authors = ["Cameron Eldridge <cameldridge+git@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.11"
hex = "0.3"
lazy_static = "1.3"
regex = "1.1"
tree-sitter = "0.3"
