[package]
name = "syncat-stylesheet"
description = "Parser for Syncat Stylesheets."
homepage = "https://github.com/foxfriends/syncat"
repository = "https://github.com/foxfriends/syncat"
version = "2.0.0"
authors = ["Cameron Eldridge <cameldridge+git@gmail.com>"]
license = "MIT"
edition = "2018"

[build-dependencies]
cc = "1.0"

[dependencies]
ansi_term = "0.12"
hex = "0.4"
regex = "1.3"
tree-sitter = "0.6"
enquote = "1.0"
