[package]
name = "syncat-stylesheet"
description = "Parser for Syncat Stylesheets."
homepage = "https://github.com/oinkiguana/syncat"
repository = "https://github.com/oinkiguana/syncat"
version = "0.2.1"
authors = ["Cameron Eldridge <cameldridge+git@gmail.com>"]
license = "MIT"
edition = "2018"

[build-dependencies]
cc = "1.0"

[dependencies]
ansi_term = "0.12"
hex = "0.4"
lazy_static = "1.4"
regex = "1.3"
tree-sitter = "0.3"
